/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/Models/model.glb -o src/components/Avatar.jsx -r public 
*/

import { useGLTF } from "@react-three/drei";
import React from "react";
import UseAvatar from "../hooks/UseAvatar";



export function ArchanaAvatar(props) {
    const think = {
        "metadata": {
          "soundFile": "C:\\Users\\PriyanshiYadav\\Downloads\\Ashish_avatar_v3 1\\Ashish_avatar_v3\\public\\audios\\justASecondAudio.ogg",
          "duration": 3.13
        },
        "mouthCues": [
          { "start": 0.00, "end": 0.06, "value": "X" },
          { "start": 0.06, "end": 0.19, "value": "B" },
          { "start": 0.19, "end": 0.26, "value": "C" },
          { "start": 0.26, "end": 0.54, "value": "B" },
          { "start": 0.54, "end": 0.61, "value": "C" },
          { "start": 0.61, "end": 0.96, "value": "B" },
          { "start": 0.96, "end": 1.37, "value": "X" },
          { "start": 1.37, "end": 1.46, "value": "H" },
          { "start": 1.46, "end": 1.53, "value": "C" },
          { "start": 1.53, "end": 1.60, "value": "B" },
          { "start": 1.60, "end": 1.68, "value": "A" },
          { "start": 1.68, "end": 1.93, "value": "B" },
          { "start": 1.93, "end": 2.07, "value": "C" },
          { "start": 2.07, "end": 2.15, "value": "A" },
          { "start": 2.15, "end": 2.25, "value": "C" },
          { "start": 2.25, "end": 2.53, "value": "F" },
          { "start": 2.53, "end": 2.67, "value": "B" },
          { "start": 2.67, "end": 2.74, "value": "F" },
          { "start": 2.74, "end": 3.09, "value": "B" },
          { "start": 3.09, "end": 3.13, "value": "X" }
        ]
      }
      

    const mouthCues =
    {
        "metadata": {
          "soundFile": "C:\\Users\\PriyanshiYadav\\Downloads\\Ashish_avatar_v3 1\\Ashish_avatar_v3\\public\\audios\\aboutInfusai-_2_.ogg",
          "duration": 26.72
        },
        "mouthCues": [
          { "start": 0.00, "end": 0.06, "value": "X" },
          { "start": 0.06, "end": 0.20, "value": "B" },
          { "start": 0.20, "end": 0.27, "value": "G" },
          { "start": 0.27, "end": 0.41, "value": "F" },
          { "start": 0.41, "end": 0.48, "value": "B" },
          { "start": 0.48, "end": 0.55, "value": "C" },
          { "start": 0.55, "end": 0.62, "value": "B" },
          { "start": 0.62, "end": 0.76, "value": "F" },
          { "start": 0.76, "end": 0.83, "value": "B" },
          { "start": 0.83, "end": 0.97, "value": "C" },
          { "start": 0.97, "end": 1.04, "value": "B" },
          { "start": 1.04, "end": 1.11, "value": "C" },
          { "start": 1.11, "end": 1.18, "value": "D" },
          { "start": 1.18, "end": 1.25, "value": "H" },
          { "start": 1.25, "end": 1.32, "value": "C" },
          { "start": 1.32, "end": 1.46, "value": "B" },
          { "start": 1.46, "end": 1.67, "value": "C" },
          { "start": 1.67, "end": 1.75, "value": "A" },
          { "start": 1.75, "end": 2.08, "value": "B" },
          { "start": 2.08, "end": 2.15, "value": "C" },
          { "start": 2.15, "end": 2.29, "value": "B" },
          { "start": 2.29, "end": 2.37, "value": "A" },
          { "start": 2.37, "end": 2.45, "value": "C" },
          { "start": 2.45, "end": 2.59, "value": "B" },
          { "start": 2.59, "end": 2.66, "value": "C" },
          { "start": 2.66, "end": 2.73, "value": "H" },
          { "start": 2.73, "end": 2.80, "value": "C" },
          { "start": 2.80, "end": 3.22, "value": "B" },
          { "start": 3.22, "end": 3.36, "value": "D" },
          { "start": 3.36, "end": 3.50, "value": "B" },
          { "start": 3.50, "end": 3.57, "value": "G" },
          { "start": 3.57, "end": 3.78, "value": "B" },
          { "start": 3.78, "end": 3.85, "value": "C" },
          { "start": 3.85, "end": 4.06, "value": "B" },
          { "start": 4.06, "end": 4.20, "value": "C" },
          { "start": 4.20, "end": 4.27, "value": "H" },
          { "start": 4.27, "end": 4.34, "value": "C" },
          { "start": 4.34, "end": 4.41, "value": "B" },
          { "start": 4.41, "end": 4.62, "value": "C" },
          { "start": 4.62, "end": 4.76, "value": "B" },
          { "start": 4.76, "end": 4.98, "value": "X" },
          { "start": 4.98, "end": 5.25, "value": "B" },
          { "start": 5.25, "end": 5.39, "value": "D" },
          { "start": 5.39, "end": 5.43, "value": "C" },
          { "start": 5.43, "end": 5.62, "value": "B" },
          { "start": 5.62, "end": 5.82, "value": "X" },
          { "start": 5.82, "end": 5.96, "value": "B" },
          { "start": 5.96, "end": 6.24, "value": "F" },
          { "start": 6.24, "end": 6.52, "value": "B" },
          { "start": 6.52, "end": 6.59, "value": "C" },
          { "start": 6.59, "end": 6.80, "value": "B" },
          { "start": 6.80, "end": 6.87, "value": "E" },
          { "start": 6.87, "end": 6.94, "value": "G" },
          { "start": 6.94, "end": 7.36, "value": "B" },
          { "start": 7.36, "end": 7.78, "value": "X" },
          { "start": 7.78, "end": 7.85, "value": "B" },
          { "start": 7.85, "end": 7.92, "value": "C" },
          { "start": 7.92, "end": 8.06, "value": "E" },
          { "start": 8.06, "end": 8.20, "value": "G" },
          { "start": 8.20, "end": 8.27, "value": "E" },
          { "start": 8.27, "end": 8.41, "value": "B" },
          { "start": 8.41, "end": 8.48, "value": "C" },
          { "start": 8.48, "end": 8.69, "value": "B" },
          { "start": 8.69, "end": 8.90, "value": "C" },
          { "start": 8.90, "end": 8.97, "value": "B" },
          { "start": 8.97, "end": 9.11, "value": "C" },
          { "start": 9.11, "end": 9.19, "value": "A" },
          { "start": 9.19, "end": 9.36, "value": "C" },
          { "start": 9.36, "end": 9.50, "value": "E" },
          { "start": 9.50, "end": 9.57, "value": "B" },
          { "start": 9.57, "end": 9.68, "value": "A" },
          { "start": 9.68, "end": 9.73, "value": "B" },
          { "start": 9.73, "end": 9.78, "value": "D" },
          { "start": 9.78, "end": 9.99, "value": "C" },
          { "start": 9.99, "end": 10.20, "value": "B" },
          { "start": 10.20, "end": 10.27, "value": "C" },
          { "start": 10.27, "end": 10.55, "value": "F" },
          { "start": 10.55, "end": 10.90, "value": "B" },
          { "start": 10.90, "end": 10.97, "value": "C" },
          { "start": 10.97, "end": 11.25, "value": "F" },
          { "start": 11.25, "end": 11.53, "value": "B" },
          { "start": 11.53, "end": 11.60, "value": "C" },
          { "start": 11.60, "end": 11.67, "value": "B" },
          { "start": 11.67, "end": 11.75, "value": "A" },
          { "start": 11.75, "end": 11.88, "value": "C" },
          { "start": 11.88, "end": 12.09, "value": "B" },
          { "start": 12.09, "end": 12.17, "value": "A" },
          { "start": 12.17, "end": 12.63, "value": "B" },
          { "start": 12.63, "end": 12.77, "value": "C" },
          { "start": 12.77, "end": 12.84, "value": "H" },
          { "start": 12.84, "end": 13.19, "value": "B" },
          { "start": 13.19, "end": 13.26, "value": "C" },
          { "start": 13.26, "end": 13.33, "value": "B" },
          { "start": 13.33, "end": 13.43, "value": "D" },
          { "start": 13.43, "end": 13.47, "value": "C" },
          { "start": 13.47, "end": 13.59, "value": "A" },
          { "start": 13.59, "end": 13.83, "value": "F" },
          { "start": 13.83, "end": 13.90, "value": "C" },
          { "start": 13.90, "end": 14.18, "value": "B" },
          { "start": 14.18, "end": 14.39, "value": "E" },
          { "start": 14.39, "end": 14.67, "value": "B" },
          { "start": 14.67, "end": 14.74, "value": "G" },
          { "start": 14.74, "end": 14.95, "value": "B" },
          { "start": 14.95, "end": 15.09, "value": "C" },
          { "start": 15.09, "end": 15.72, "value": "B" },
          { "start": 15.72, "end": 16.13, "value": "X" },
          { "start": 16.13, "end": 16.30, "value": "B" },
          { "start": 16.30, "end": 16.37, "value": "G" },
          { "start": 16.37, "end": 16.51, "value": "F" },
          { "start": 16.51, "end": 16.65, "value": "B" },
          { "start": 16.65, "end": 16.72, "value": "C" },
          { "start": 16.72, "end": 16.93, "value": "B" },
          { "start": 16.93, "end": 17.21, "value": "F" },
          { "start": 17.21, "end": 17.49, "value": "B" },
          { "start": 17.49, "end": 17.63, "value": "E" },
          { "start": 17.63, "end": 17.70, "value": "G" },
          { "start": 17.70, "end": 17.98, "value": "B" },
          { "start": 17.98, "end": 18.05, "value": "G" },
          { "start": 18.05, "end": 18.19, "value": "E" },
          { "start": 18.19, "end": 18.40, "value": "B" },
          { "start": 18.40, "end": 18.48, "value": "A" },
          { "start": 18.48, "end": 18.54, "value": "C" },
          { "start": 18.54, "end": 18.80, "value": "B" },
          { "start": 18.80, "end": 18.87, "value": "C" },
          { "start": 18.87, "end": 19.15, "value": "E" },
          { "start": 19.15, "end": 19.65, "value": "B" },
          { "start": 19.65, "end": 19.71, "value": "C" },
          { "start": 19.71, "end": 19.84, "value": "D" },
          { "start": 19.84, "end": 20.05, "value": "B" },
          { "start": 20.05, "end": 20.12, "value": "E" },
          { "start": 20.12, "end": 20.19, "value": "F" },
          { "start": 20.19, "end": 20.26, "value": "C" },
          { "start": 20.26, "end": 20.40, "value": "B" },
          { "start": 20.40, "end": 20.47, "value": "F" },
          { "start": 20.47, "end": 20.54, "value": "B" },
          { "start": 20.54, "end": 20.65, "value": "A" },
          { "start": 20.65, "end": 20.72, "value": "B" },
          { "start": 20.72, "end": 20.78, "value": "D" },
          { "start": 20.78, "end": 21.31, "value": "B" },
          { "start": 21.31, "end": 21.51, "value": "C" },
          { "start": 21.51, "end": 21.59, "value": "A" },
          { "start": 21.59, "end": 21.74, "value": "F" },
          { "start": 21.74, "end": 21.95, "value": "E" },
          { "start": 21.95, "end": 22.02, "value": "G" },
          { "start": 22.02, "end": 22.16, "value": "B" },
          { "start": 22.16, "end": 22.37, "value": "C" },
          { "start": 22.37, "end": 22.61, "value": "B" },
          { "start": 22.61, "end": 22.67, "value": "C" },
          { "start": 22.67, "end": 22.72, "value": "B" },
          { "start": 22.72, "end": 22.93, "value": "C" },
          { "start": 22.93, "end": 23.21, "value": "B" },
          { "start": 23.21, "end": 23.35, "value": "C" },
          { "start": 23.35, "end": 23.49, "value": "B" },
          { "start": 23.49, "end": 23.68, "value": "C" },
          { "start": 23.68, "end": 23.74, "value": "F" },
          { "start": 23.74, "end": 23.94, "value": "B" },
          { "start": 23.94, "end": 24.15, "value": "F" },
          { "start": 24.15, "end": 24.22, "value": "B" },
          { "start": 24.22, "end": 24.29, "value": "H" },
          { "start": 24.29, "end": 24.36, "value": "C" },
          { "start": 24.36, "end": 24.71, "value": "B" },
          { "start": 24.71, "end": 24.78, "value": "C" },
          { "start": 24.78, "end": 24.92, "value": "B" },
          { "start": 24.92, "end": 24.99, "value": "G" },
          { "start": 24.99, "end": 25.13, "value": "B" },
          { "start": 25.13, "end": 25.41, "value": "F" },
          { "start": 25.41, "end": 25.55, "value": "B" },
          { "start": 25.55, "end": 25.76, "value": "F" },
          { "start": 25.76, "end": 25.83, "value": "B" },
          { "start": 25.83, "end": 25.90, "value": "C" },
          { "start": 25.90, "end": 25.97, "value": "B" },
          { "start": 25.97, "end": 26.18, "value": "H" },
          { "start": 26.18, "end": 26.25, "value": "C" },
          { "start": 26.25, "end": 26.32, "value": "B" },
          { "start": 26.32, "end": 26.46, "value": "C" },
          { "start": 26.46, "end": 26.67, "value": "B" },
          { "start": 26.67, "end": 26.72, "value": "X" }
        ]
      }
      





    const { nodes, materials, group } = UseAvatar({
        modelPath: "/models/ArchanaAvatar.glb",
        idleAnimationPath: "/animations/AshishIdlePose.glb",
        thinkAnimationPath: "/animations/Ashish_thinking.glb",
        salaamAnimationPath: "/animations/Salaam6_defaultNew.glb",

        audioSrc: "\\audios\\aboutInfusai-_2_.ogg",
        mouthCues: mouthCues,
        thinkAudio: "\\audios\\justASecondAudio.ogg",
        think: think,
        gender: "female",
    });

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="Armature">
                    <primitive object={nodes.Hips} />
                    {/* Archana avatar code */}
                    <skinnedMesh
                        geometry={nodes.Body_Mesh.geometry}
                        material={materials.Body}
                        skeleton={nodes.Body_Mesh.skeleton}
                    />
                    <skinnedMesh
                        name="Eye_Mesh"
                        geometry={nodes.Eye_Mesh.geometry}
                        material={materials.Eyes}
                        skeleton={nodes.Eye_Mesh.skeleton}
                        morphTargetDictionary={nodes.Eye_Mesh.morphTargetDictionary}
                        morphTargetInfluences={nodes.Eye_Mesh.morphTargetInfluences}
                    />
                    <skinnedMesh
                        name="EyeAO_Mesh"
                        geometry={nodes.EyeAO_Mesh.geometry}
                        material={materials.EyeAO}
                        skeleton={nodes.EyeAO_Mesh.skeleton}
                        morphTargetDictionary={nodes.EyeAO_Mesh.morphTargetDictionary}
                        morphTargetInfluences={nodes.EyeAO_Mesh.morphTargetInfluences}
                    />
                    <skinnedMesh
                        name="Eyelash_Mesh"
                        geometry={nodes.Eyelash_Mesh.geometry}
                        material={materials.Eyelash}
                        skeleton={nodes.Eyelash_Mesh.skeleton}
                        morphTargetDictionary={nodes.Eyelash_Mesh.morphTargetDictionary}
                        morphTargetInfluences={nodes.Eyelash_Mesh.morphTargetInfluences}
                    />
                    <skinnedMesh
                        name="Head_Mesh"
                        geometry={nodes.Head_Mesh.geometry}
                        material={materials.Head}
                        skeleton={nodes.Head_Mesh.skeleton}
                        morphTargetDictionary={nodes.Head_Mesh.morphTargetDictionary}
                        morphTargetInfluences={nodes.Head_Mesh.morphTargetInfluences}
                    />
                    <skinnedMesh
                        name="Teeth_Mesh"
                        geometry={nodes.Teeth_Mesh.geometry}
                        material={materials.Teeth}
                        skeleton={nodes.Teeth_Mesh.skeleton}
                        morphTargetDictionary={nodes.Teeth_Mesh.morphTargetDictionary}
                        morphTargetInfluences={nodes.Teeth_Mesh.morphTargetInfluences}
                    />
                    <skinnedMesh
                        name="Tongue_Mesh"
                        geometry={nodes.Tongue_Mesh.geometry}
                        material={materials.Teeth}
                        skeleton={nodes.Tongue_Mesh.skeleton}
                        morphTargetDictionary={nodes.Tongue_Mesh.morphTargetDictionary}
                        morphTargetInfluences={nodes.Tongue_Mesh.morphTargetInfluences}
                    />
                    <skinnedMesh
                        geometry={nodes.avaturn_hair_0.geometry}
                        material={materials.avaturn_hair_0_material}
                        skeleton={nodes.avaturn_hair_0.skeleton}
                    />
                    <skinnedMesh
                        geometry={nodes.avaturn_hair_1.geometry}
                        material={materials.avaturn_hair_1_material}
                        skeleton={nodes.avaturn_hair_1.skeleton}
                    />
                    <skinnedMesh
                        geometry={nodes.avaturn_shoes_0.geometry}
                        material={materials.avaturn_shoes_0_material}
                        skeleton={nodes.avaturn_shoes_0.skeleton}
                    />
                    <skinnedMesh
                        geometry={nodes.avaturn_look_0.geometry}
                        material={materials.avaturn_look_0_material}
                        skeleton={nodes.avaturn_look_0.skeleton}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/ArchanaAvatar.glb')
